version: '3'

services:

  php:
    build: docker/php
    volumes:
      - ./app:/var/www/html
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./data/logs/php:/var/log/php
    env_file:
      - .env
    environment:
      - ${MYSQL_PORT}=mysql

  nginx:
    image: nginx:latest
    ports:
      - '443:443'
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./app/:/var/www/html"
      - "./ssl/:/etc/nginx/ssl"
    links:
      - php
    restart: always


  #  localtunnel:
  #    image: efrecon/localtunnel
  #    links:
  #      - apache
  #    command:
  #      --local-host apache --port 80

  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./database-dump:/database-dump
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  node:
    image: jujhars13/docker-node-npm-bower-gulp
    volumes:
      - ./app:/data
    command: tail -f /dev/null



  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql:3306
    ports:
      - ${PHPMYADMIN_PORT}:8080

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
      - "1025:1025"
